# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcd44d5e6646ee4de714975ecc86a635cfccf17d865be83baf7f0049c6d610918619ce62fb92961597ea3974b5cada70693adc656822bce30315c96efee700a5

test:
  secret_key_base: e9742b880be7d1492e799a184b44c9fac7fe4304354dab979e2b11950a2b8ea4ff4f2a8cb6d013f42cc70ebf4deefd1b8bd4f1117d694e178fd285184cf9d461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
